In [1]:
print("techfor.id")

techfor.id


In [2]:
nama = "techfor.id"

In [3]:
print (nama)

techfor.id


In [4]:
#untuk memulai numpy kita perlu meng-importnya
import numpy as np

In [5]:
data = [1,2,3] #data list pada python
data

[1, 2, 3]

In [6]:
np.array(data) #list di convert ke dalam array numpy

array([1, 2, 3])

In [7]:
#membuat data array numpy otomatis
np.arange(0,10) #0 adalah batas awal dan 10 adalah batas akhir

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2) #2 di belakang adlah kelipatan

array([0, 2, 4, 6, 8])

In [9]:
#membuat array dummy
np.linspace(0,10,3) #0 adalah batas awalnya, 10 adalah batas akhirnya, dan 3 adlah jumlah array dummy nya


array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50) #semakin banyak jumlah arraynya maka semakin banyak pula angka komanya

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [14]:
np.random.rand(3) #membuat array random 3 kolom

array([0.73886371, 0.69096583, 0.02670187])

In [15]:
np.random.rand(3,3) #membuat data array 3 baris dan 3 kolom

array([[0.97974488, 0.91229359, 0.65913785],
       [0.38391149, 0.35192109, 0.01585103],
       [0.75702509, 0.73286348, 0.67517563]])

In [17]:
np.random.randn(3,3) #membuat data array 3 baris 3 kolom secara bilangan positif dan negatif

array([[ 0.14479445, -0.39421253, -2.67817761],
       [ 2.09551701, -0.11700928,  0.76374161],
       [ 0.0754704 , -0.25342847,  0.11963998]])

In [18]:
np.random.randint(1,50) #membuat data random antara 1 sampai 50

12

In [19]:
np.random.randint(1,50,10) #membuat data array random 10 kolom

array([49,  7, 14, 29, 42, 49, 39, 38, 41, 32])

In [20]:
#Reshpe (merubah tampilan array perbaris dan perkolom)

In [21]:
arr = np.arange(25) #membuat array numpy

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
arr.reshape(5,5) #merubah tampilan arr yang sudah di buat menjadi 5 baris dan 5 kolom

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [27]:
newArr = arr.reshape(5,5)

In [28]:
print(newArr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [35]:
newArr[1][4]=99

In [36]:
print(newArr)

[[ 0  1  2  3  4]
 [ 5  6  7  8 99]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [38]:
arr.max()

99

In [39]:
print(arr)

[ 0  1  2  3  4  5  6  7  8 99 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [40]:
arr.min()

0

In [41]:
arr.argmax()

9

In [42]:
arr.sum()

390

In [43]:
newArr.max()

99